### ISSUE TITLE
cannot roslaunch map.py

### ISSUE THREAD

**Issue by Akashleena** [yuchnw/quadSimulator#1]
i did roslaunch iris_sim map.py
I am getting this error:
Traceback (most recent call last):
  File "/home/aleena/catkin_ws/src/quadcoptersimulation/src/map.py", line 9, in <module>
    from iris_sim.msg import Progress,Feedback
ModuleNotFoundError: No module named 'iris_sim'

**Comment by Ayush1285** [comment]
> i did roslaunch iris_sim map.py
> I am getting this error:
> Traceback (most recent call last):
> File "/home/aleena/catkin_ws/src/quadcoptersimulation/src/map.py", line 9, in
> from iris_sim.msg import Progress,Feedback
> ModuleNotFoundError: No module named 'iris_sim'

What's name of your package in package.xml?

**Comment by Akashleena** [comment]
I sorted it. I had messed up with the installation. Also, on Ubuntu 18.04 I had to install some dependencies, I have updated those in a file, and I will send you a PR soon.
